apiVersion: v1
kind: Service
metadata:
  name: workshopnamespacevalidator
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    run: workshopnamespacevalidator
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: workshopnamespacevalidator
  name: workshopnamespacevalidator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: workshopnamespacevalidator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: workshopnamespacevalidator
    spec:
      containers:
      - image: lalyos/k8s-ns-admission
        name: workshopnamespacevalidator
        args:
            - -tls-cert-file=/etc/webhook/certs/cert.pem
            - -tls-private-key-file=/etc/webhook/certs/key.pem
            - -stderrthreshold=INFO
            - -v=6
        ports:
        - containerPort: 443
        volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
        resources: {}
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-webhook-example-certs