apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: workshopnamespacevalidator
webhooks:
  - clientConfig:
      service:
        namespace: default
        name: workshopnamespacevalidator 
        path: /ns
      caBundle: $CABUNDLE
    name: ns.workshop.com
    rules:
      - apiGroups:
        - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - DELETE
          - UPDATE
        resources:
          - namespaces