apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: workshopnamespacevalidator
webhooks:
  - clientConfig:
      service:
        namespace: default
        name: workshopnamespacevalidator 
        path: /ns
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQVAvK0Niei9PZVZ2RTFJRHgwNkpobG93RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa05HRmhOMlV6TlRndFl6UTVZaTAwWldGbExXRmxNbUV0WXpnM01XWm1OVFUyWlRRMApNQjRYRFRFNE1URXdPVEl4TWpneE4xb1hEVEl6TVRFd09ESXlNamd4TjFvd0x6RXRNQ3NHQTFVRUF4TWtOR0ZoCk4yVXpOVGd0WXpRNVlpMDBaV0ZsTFdGbE1tRXRZemczTVdabU5UVTJaVFEwTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbjhQQkhnaDE5MHl1WjU0Zk9zalZyRHRNSC9SN0o2NnY4Q0NqNytsRwpyNkJWeTh1UlM2em1RUVdnSEVaNUtoaVNORHl1NVpBS2RVN0Npa2RlYXN6SDdTWFBnalJPVVVWZ3FRWWwvc2tWCm5TOUcxcktMV1dFYVBLeW5FVTRlSjhzNWtRSzhncDhqZWdXV2JUVnZTTk1mQ2hKWkdXcGkxaFRhS05nc1lJMUUKQkJqUTVXeXAvTURvMFZLM3ZZSDUwWk5kNlJoc01QYTZHMXhHbE82VU9IekRXL080RVBscVFONmFLd2ZNM0ZkQQo3TVhZRkN2NVdzMXFqWko5eS9yMlJPTHFnQVVDVXY1d1FmNzNITFlXQWVHdE5WWk16dGwwRnhNQndubS9lZER2CkExYXZMSUg5VTg4NGsvc2N6OGRzS2x0dTdEUEpzaTJ3NEtzKy9vbnVKVVBuL1FJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpsdzdHMVJSemVsWEdGVUF0T0VYYzBxTE5oOFJNd1l1STNsL1czRWVzMnpYcS9VT0NKTnNOeCtvbjY0ZXFBaXpKCmRqdVFJQVFvNDdnVlRjNHhySUI3SGJCWmcramIySFlqOG1rbWRRcHhxSDcyV0J5TkE5K0dCN0RqWFFuME9Xa0sKbHpPbDk1RDZnNjVLdHpOdGpSNGxNcXlVeFU0UVZzNnhNaVBTUTg3NnRuVnlvcUhyTktmNGJ5aEZvZHA2UUdBNgpNQVRaWENNTGVsUlFZTCtnaVNPcktZc214djgzSStsYmM5WjNDUFgybzBBNDdWdEExU3hVWVNpN2U0dU5uQk5VCmtEdHAwYXpiM2ZwaDVoclh0TmFtQzdNeHFWamxsc3phQ1VRODFtNzNpNG9OL2ZQYlZrZjZCeWZyaDRCc0RCOXkKKzFKc00ra3hzNS9LR1hvWUxkRElZQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    name: ns.workshop.com
    rules:
      - apiGroups:
        - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - DELETE
          - UPDATE
        resources:
          - namespaces